### ISSUE TITLE
3 חדרים, 60 מטר ברחוב בן צדוק

### ISSUE THREAD

**Issue by AvivRubys** [AvivRubys/apartments#165]
[http://www.yad2.co.il/Nadlan/tivrent_info.php?NadlanID=924814](http://www.yad2.co.il/Nadlan/tivrent_info.php?NadlanID=924814)

**Comment by laenaren** [comment]
לא מבינים כלום מהתמונות 
זה רק המטבח
ומלא רצפה

**Comment by AvivRubys** [comment]
תכלס
