### ISSUE TITLE
2 חדרים, 70 מטר ברחוב הקישון

### ISSUE THREAD

**Issue by AvivRubys** [AvivRubys/apartments#166]
[http://www.yad2.co.il/Nadlan/tivrent_info.php?NadlanID=918627](http://www.yad2.co.il/Nadlan/tivrent_info.php?NadlanID=918627)

**Comment by AvivRubys** [comment]
תכלס לא אהבתי

**Comment by laenaren** [comment]
אםשרי לגמרי לדעתי
היא גדולה אז בטוח נצליח לדחוך את המחשבים איכשהו
צריך לראות בשביל להבין מה גודל של כל חדר
