### ISSUE TITLE
2.5 חדרים, 70 מטר ברחוב הרצל

### ISSUE THREAD

**Issue by AvivRubys** [AvivRubys/apartments#168]
[http://www.yad2.co.il/Nadlan/tivrent_info.php?NadlanID=914211](http://www.yad2.co.il/Nadlan/tivrent_info.php?NadlanID=914211)

**Comment by laenaren** [comment]
ואללה זו ממש יפה
תיווך אבל. לא קצת יקר?

**Comment by AvivRubys** [comment]
לא שמתי לב, כבר מבולבל מרוב דירות, עם התיווך זה מביא אותנו לבערך כמה שאנחנו משלמים עכשיו...
