### ISSUE TITLE
3 חדרים, 65 מטר ברחוב הרצל

### ISSUE THREAD

**Issue by AvivRubys** [AvivRubys/apartments#169]
[http://www.yad2.co.il/Nadlan/rent_info.php?NadlanID=3203898](http://www.yad2.co.il/Nadlan/rent_info.php?NadlanID=3203898)

**Comment by laenaren** [comment]
זו יפה!

**Comment by AvivRubys** [comment]
אני אנסה להגיע לשם היום, נראה אם אפשר

**Comment by AvivRubys** [comment]
היום ב7
